# Generated by Django 3.0.4 on 2021-02-08 23:36

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=80, verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'categorias',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Galerias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=80, verbose_name='Nombre Galería')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
                ('imagen_principal', models.ImageField(blank=True, null=True, upload_to='')),
                ('status', models.BooleanField(default=True, verbose_name='Estatus Galería')),
            ],
            options={
                'verbose_name': 'Galeria',
                'verbose_name_plural': 'Galerias',
                'db_table': 'galerias',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=80, null=True, verbose_name='Titulo Youtube')),
                ('link', models.CharField(blank=True, max_length=120, null=True, verbose_name='Link Youtube')),
                ('status', models.BooleanField(default=True, verbose_name='Estatus Link Youtube')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'db_table': 'videos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', ckeditor.fields.RichTextField()),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('imagen_principal', models.ImageField(upload_to='')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
                ('status', models.BooleanField(default=True, verbose_name='Estatus Publicación')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina.Categoria')),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
                'db_table': 'noticias',
                'ordering': ['id'],
            },
        ),
    ]
