# Generated by Django 3.0.2 on 2021-06-01 22:37

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0002_catalogogalerias'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Nombre Evento')),
                ('contenido', ckeditor.fields.RichTextField()),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('imagen_principal', models.ImageField(upload_to='')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
                ('status', models.BooleanField(default=True, verbose_name='Estatus Publicación')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'db_table': 'eventos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Talleres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Nombre Taller')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('imagen_principal', models.ImageField(upload_to='')),
                ('link', models.CharField(blank=True, max_length=120, null=True, verbose_name='Link del Taller')),
                ('status', models.BooleanField(default=True, verbose_name='Estatus Publicación')),
            ],
            options={
                'verbose_name': 'Taller',
                'verbose_name_plural': 'Talleres',
                'db_table': 'talleres',
                'ordering': ['id'],
            },
        ),
    ]
