# Generated by Django 3.0.2 on 2021-06-01 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0004_talleres_autor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talleres',
            name='imagen_principal',
        ),
    ]
